version: '3.3'

services:
  db1:
    image: mysql:5.7
    environment:
      # Neue DB mit dem Namen test (Achtung case-sensitive) anlegen
      MYSQL_DATABASE: 'test'
      # Neuer User für die DB test, keine Root rechte außerhalb
      MYSQL_USER: 'root2'
      # Passwort für den neuen User
      MYSQL_PASSWORD: '1234'
      # Passwort für den Standard-DB-Root user root setzen
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db1:/var/lib/mysql1
      
# Names our volume
volumes:
  my-db1: